apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: test-hcp-vlan10
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.20.32-x86_64
  dns:
    baseDomain: lab.signal9.gg
  infraID: test-hcp-vlan10
  controllerAvailabilityPolicy: SingleReplica
  infrastructureAvailabilityPolicy: SingleReplica
  olmCatalogPlacement: guest
  fips: false
  etcd:
    managementType: Managed
    managed:
      storage:
        type: PersistentVolume
        persistentVolume:
          size: 8Gi
  networking:
    networkType: OVNKubernetes
    clusterNetwork:
      - cidr: 10.132.0.0/14
    serviceNetwork:
      - cidr: 172.31.0.0/16
  platform:
    type: KubeVirt
    kubevirt:
      baseDomainPassthrough: true
  pullSecret:
    name: test-hcp-vlan10-pull-secret
  sshKey:
    name: test-hcp-vlan10-ssh-key
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
        loadBalancer:
          hostname: api.test-hcp-vlan10.lab.signal9.gg
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: OIDC
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
