apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: test-hcp-vlan10-workers
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: '3'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterName: test-hcp-vlan10
  replicas: 3
  arch: amd64
  management:
    autoRepair: false
    upgradeType: Replace
  platform:
    type: KubeVirt
    kubevirt:
      compute:
        cores: 2
        memory: 8Gi
      rootVolume:
        type: Persistent
        persistent:
          size: 120Gi
          storageClass: ocs-external-storagecluster-ceph-rbd
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.20.32-x86_64
