apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-hcp-vlan10-pull-secret
  namespace: clusters
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: test-hcp-vlan10-pull-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: ocp-pull-secret
