{{- if .Values.monitoring.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
{{ if .Values.monitoring.userWorkloadMonitoring }}
    enableUserWorkload: true
    alertmanagerMain:
      enableUserAlertmanagerConfig: true
{{ else }}
    alertmanagerMain:
{{ end }}
{{- if .Values.monitoring.infraNodePlacement }}
{{ include "ocp-base-config.infraPlacement" . | indent 6 }}
{{- end }}
      volumeClaimTemplate:
       spec:
         storageClassName: {{ .Values.monitoring.storageClass }}
         resources:
           requests:
             storage: {{ .Values.monitoring.alertManagerSize }}
    prometheusK8s:
      retention: 7d
{{- if .Values.monitoring.infraNodePlacement }}
{{ include "ocp-base-config.infraPlacement" . | indent 6 }}
{{- end }}
      volumeClaimTemplate:
       spec:
         storageClassName: {{ .Values.monitoring.storageClass }}
         resources:
           requests:
             storage: {{ .Values.monitoring.prometheusSize }}
{{- if .Values.monitoring.infraNodePlacement }}
{{- range tuple "prometheusOperator" "kubeStateMetrics" "openshiftStateMetrics" "telemeterClient" "thanosQuerier" "metricsServer" "monitoringPlugin" }}
    {{ . }}:
{{ include "ocp-base-config.infraPlacement" $ | indent 6 }}
{{- end }}
{{- end }}
{{ end }}
