apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: hub
  namespace: rhacm-hub
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  availabilityConfig: Basic
  localClusterName: test-hcp-foundation
